### ISSUE TITLE
Support for multiple `random` components?

### ISSUE THREAD

**Issue by santikka** [ropensci/dynamite#38]
If I understand correctly, it is currently possible to only add a single `random` component to the model. How does one then specify, for example, correlated random intercepts between two channels, and a separate uncorrelated random intercept for a third channel? Should we try to support this?

**Comment by helske** [comment]
Yes, you're right, the current `random` is lacking in the sense that either all or none of the intercepts are correlated. For completeness, I think supporting something like your example would be a good idea, but on the other hand, I'm not sure how realistic/common such a situation would be where you want to allow some of the channels to correlate but you know for a certain that one channel is not correlated with the others?

**Comment by santikka** [comment]
True, that example was probably not a very realistic scenario, but I could imagine having some intracorrelated channel "groups" that are not correlated with each other.

**Comment by santikka** [comment]
We now have `random()` for the model formulas.
