### ISSUE TITLE
Use array keyword for arrays

### ISSUE THREAD

**Issue by helske** [ropensci/dynamite#49]
As warned by  `cmdstanr`:

>Declaration of arrays by placing brackets after a variable name is deprecated and will be removed in Stan 2.32.0. Instead use the array keyword before the type.`

https://mc-stan.org/docs/2_30/reference-manual/array-data-types.html

**Comment by helske** [comment]
Except this is likely not compatible with rstan/Stanheaders versions on CRAN so let's hold on for now in case we work out the other backward compatibility issues...

**Comment by santikka** [comment]
Let's keep backward compatibility by switching the definitions based on the users' backend Stan version.

**Comment by santikka** [comment]
Implemented in e2c2d872fb7259608c8b408986c59d77a4d232f9
