### ISSUE TITLE
Math not rendering on pkgdown website

### ISSUE THREAD

**Issue by Aariq** [ropensci/dynamite#54]
It looks like the in-line math in the "get started" section on the website isn't rendering correctly.

**Comment by helske** [comment]
Not completed...

**Comment by helske** [comment]
I didn't realize we need to provide `_pkgdown.yml` with `mathjax: true` in order to render math. Should work now after the `r-universe` build finishes.

**Comment by santikka** [comment]
The in-line math seems to be working now.
