### ISSUE TITLE
Probit ordered specification

### ISSUE THREAD

**Issue by DjakissO** [ropensci/dynamite#79]
Hi,
I want to fit a Bayesian dynamic ordered panel probit. I've read the Tikka and Helske （2023） guide but haven't seen how to specify an ordered probit. So I would like to know if I can use dynamite to specify the ordinal nature of my dependent variable, and if so, how.
Many thanks for considering my request.

**Comment by santikka** [comment]
Hi @DjakissO ! Unfortunately, ordered probit is not currently supported, but we have plans to add this feature (probably soon), especially if there is interest in this feature.

**Comment by DjakissO** [comment]
Hi @***@***.***>,

Thank you for your feedback. I want to know if there is another Bayesian approach package that can support panel ordered probit.

Best regards,
Djakalia
________________________________

**Comment by santikka** [comment]
@DjakissO Ordered probit and logit are now available in dynamite, you can write, e.g., 
`obs(y ~ x, family = "cumulative", link = "probit")`
The response for such a channel should be an ordered factor in the data. Please keep in mind that this feature is not yet extensively tested.

**Comment by DjakissO** [comment]
Hi,

Wow! That's great news. Thank you very much for the information.

All the best,
Djakalia

Le mer. 24 avr. 2024, 14:52, Santtu Tikka ***@***.***> a
écrit :

**Comment by DjakissO** [comment]
Hi @santikka,
I tried to run it but ti returns the following error message: unused argument (link = "probit").  What can I do to resolve this error ?

**Comment by santikka** [comment]
Hi @DjakissO, please install the latest development version of dynamite, as this update is not yet on CRAN:
`devtools::install_github("ropensci/dynamite")`

**Comment by DjakissO** [comment]
It's perfect now. Thank you for your help, and especially for your diligence.
________________________________

**Comment by santikka** [comment]
Closing this as completed.
